name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"


name: hello-Vamsi
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-stepvamsi
        run: echo "Hello Vamsi!"
